### ISSUE TITLE
引导双系统

### ISSUE THREAD

**Issue by anhoder** [echokk11/MSI-B560m-Bomb_i5-10400f_5700xt#1]
请问你是怎么引导双系统的，我是单硬盘Mac+Windows双系统，现在是用EasyUEFI添加的OC引导项，但是在启动时有时会卡在微星logo进不去引导，有遇到过吗

**Comment by echokk11** [comment]
我还没有双系统的需求，就一个macOS，不过双系统我还是建议2块硬盘，方便一些。
